import * as vscode from 'vscode';

export const syntaxKeywords = [
    { text: 'Algoritmo', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Inicio', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Registro', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Si', kind: vscode.CompletionItemKind.Keyword },
    { text: 'En_Caso', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Funcion', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Procedimiento', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Mientras', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Para', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Repetir', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Fin', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Fin_Registro', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Fin_Si', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Fin_Caso', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Fin_Funcion', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Fin_Procedimiento', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Fin_Mientras', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Fin_Para', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Fin_Repetir', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Var', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Mostrar', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Imprimir', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Leer', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Entonces', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Sino', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Hasta', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Devolver', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Hacer', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Caso', kind: vscode.CompletionItemKind.Keyword },
    { text: 'Sea', kind: vscode.CompletionItemKind.Keyword },

    { text: 'Entero', kind: vscode.CompletionItemKind.Class },
    { text: 'Real', kind: vscode.CompletionItemKind.Class },
    { text: 'Caracter', kind: vscode.CompletionItemKind.Class },
    { text: 'Cadena', kind: vscode.CompletionItemKind.Class },
    { text: 'Booleano', kind: vscode.CompletionItemKind.Class },

    { text: 'Mod', kind: vscode.CompletionItemKind.Operator },
    { text: 'And', kind: vscode.CompletionItemKind.Operator },
    { text: 'Or', kind: vscode.CompletionItemKind.Operator },

    { text: 'E', kind: vscode.CompletionItemKind.TypeParameter },
    { text: 'S', kind: vscode.CompletionItemKind.TypeParameter },
    { text: 'E/S', kind: vscode.CompletionItemKind.TypeParameter },
];
