import { CompletionItemKind } from 'vscode';
import type { KeywordEntry } from '../types';

export const keywords: KeywordEntry[] = [
  { text: 'Algoritmo', kind: CompletionItemKind.Keyword },
  { text: 'Inicio', kind: CompletionItemKind.Keyword },
  { text: 'Registro', kind: CompletionItemKind.Keyword },
  { text: 'Si', kind: CompletionItemKind.Keyword },
  { text: 'En_Caso', kind: CompletionItemKind.Keyword },
  { text: 'Funcion', kind: CompletionItemKind.Keyword },
  { text: 'Procedimiento', kind: CompletionItemKind.Keyword },
  { text: 'Mientras', kind: CompletionItemKind.Keyword },
  { text: 'Para', kind: CompletionItemKind.Keyword },
  { text: 'Repetir', kind: CompletionItemKind.Keyword },
  { text: 'Fin', kind: CompletionItemKind.Keyword },
  { text: 'Fin_Registro', kind: CompletionItemKind.Keyword },
  { text: 'Fin_Si', kind: CompletionItemKind.Keyword },
  { text: 'Fin_Caso', kind: CompletionItemKind.Keyword },
  { text: 'Fin_Funcion', kind: CompletionItemKind.Keyword },
  { text: 'Fin_Procedimiento', kind: CompletionItemKind.Keyword },
  { text: 'Fin_Mientras', kind: CompletionItemKind.Keyword },
  { text: 'Fin_Para', kind: CompletionItemKind.Keyword },
  { text: 'Fin_Repetir', kind: CompletionItemKind.Keyword },
  { text: 'Var', kind: CompletionItemKind.Keyword },
  { text: 'Mostrar', kind: CompletionItemKind.Keyword },
  { text: 'Imprimir', kind: CompletionItemKind.Keyword },
  { text: 'Leer', kind: CompletionItemKind.Keyword },
  { text: 'Entonces', kind: CompletionItemKind.Keyword },
  { text: 'Sino', kind: CompletionItemKind.Keyword },
  { text: 'Hasta', kind: CompletionItemKind.Keyword },
  { text: 'Devolver', kind: CompletionItemKind.Keyword },
  { text: 'Hacer', kind: CompletionItemKind.Keyword },
  { text: 'Caso', kind: CompletionItemKind.Keyword },
  { text: 'Sea', kind: CompletionItemKind.Keyword },

  { text: 'Entero', kind: CompletionItemKind.Class },
  { text: 'Real', kind: CompletionItemKind.Class },
  { text: 'Caracter', kind: CompletionItemKind.Class },
  { text: 'Cadena', kind: CompletionItemKind.Class },
  { text: 'Booleano', kind: CompletionItemKind.Class },

  { text: 'Mod', kind: CompletionItemKind.Operator },
  { text: 'And', kind: CompletionItemKind.Operator },
  { text: 'Or', kind: CompletionItemKind.Operator },

  { text: 'E', kind: CompletionItemKind.TypeParameter },
  { text: 'S', kind: CompletionItemKind.TypeParameter },
  { text: 'E/S', kind: CompletionItemKind.TypeParameter },
];
